### ISSUE TITLE
Add option to swap the sound to a custom file

### ISSUE THREAD

**Issue by frarg** [jarrodcabalzar/CasketSounds#1]
Pretty self explanatory, and I think adding this feature would be fairly simple.

**Comment by jarrodcabalzar** [comment]
Hi @frarg, you can do this yourself by replacing any of the files in _C:\Users\user\\.runelite\casket-sounds_. The plugin picks one of them at random so if you have just 1 sound you want to play, you can replace all of them with the same file. Hope this helps.
